"""
services/story_generator.py — Multi-provider story generation service (Grok / Groq).

Supports xAI Grok and Groq API. Both are OpenAI-API-compatible.
Prioritizes Groq if available due to its extreme performance and reliability.
Supports style, length, and language customization.
"""

from __future__ import annotations

import logging
import time
from typing import Any

from openai import APIConnectionError, APIStatusError, OpenAI, RateLimitError

from config import (
    GROK_API_KEY,
    GROK_BASE_URL,
    GROK_MODEL,
    GROK_TEMPERATURE,
    GROQ_API_KEY,
    GROQ_BASE_URL,
    GROQ_MODEL,
    GROQ_TEMPERATURE,
    GROK_MAX_RETRIES,
    STORY_LENGTHS,
    STORY_STYLES,
)

logger = logging.getLogger(__name__)


def _build_client() -> tuple[OpenAI, str, str]:
    """
    Build a configured OpenAI client based on available API keys.
    Prioritizes Groq if GROQ_API_KEY is present.

    Returns:
        tuple: (OpenAI client, model_id, provider_name)

    Raises:
        ValueError: If neither GROK_API_KEY nor GROQ_API_KEY is set.
    """
    # 1. Groq Check (Primary recommendation for speed/stability)
    if GROQ_API_KEY:
        logger.info("Using Groq provider (%s)", GROQ_MODEL)
        return (
            OpenAI(api_key=GROQ_API_KEY, base_url=GROQ_BASE_URL),
            GROQ_MODEL,
            "Groq",
        )

    # 2. Grok Check (Fallback)
    if GROK_API_KEY:
        logger.info("Using Grok provider (%s)", GROK_MODEL)
        return (
            OpenAI(api_key=GROK_API_KEY, base_url=GROK_BASE_URL),
            GROK_MODEL,
            "Grok",
        )

    raise ValueError(
        "No API keys found for story generation. "
        "Please add GROQ_API_KEY or GROK_API_KEY to your .env file."
    )


def _build_prompt(
    caption: str,
    style_key: str,
    length_key: str,
    language: str,
) -> str:
    """
    Construct the story-generation prompt from user selections.
    """
    style_info = STORY_STYLES.get(style_key, STORY_STYLES["🎭 Dramatic"])
    length_info = STORY_LENGTHS.get(length_key, STORY_LENGTHS["Medium (≈150 words)"])

    word_count: int = length_info["words"]
    style_instruction: str = style_info["instruction"]
    lang_clause = f"Write the story in {language}. " if language != "English" else ""

    return (
        f"You are a master storyteller.\n"
        f"{lang_clause}"
        f"{style_instruction}\n\n"
        f"Based on the following scene description, write an original story of "
        f"approximately {word_count} words.\n\n"
        f"Scene: {caption}\n\n"
        f"Story:"
    )


def generate_story(
    caption: str,
    style_key: str = "🎭 Dramatic",
    length_key: str = "Medium (≈150 words)",
    language: str = "English",
) -> str:
    """
    Generate a story from a scene caption using the best available LLM provider.
    """
    try:
        client, model, provider = _build_client()
    except ValueError as exc:
        logger.error("Provider initialization failed: %s", exc)
        raise exc

    prompt = _build_prompt(caption, style_key, length_key, language)
    length_info = STORY_LENGTHS.get(length_key, STORY_LENGTHS["Medium (≈150 words)"])
    max_tokens = length_info["words"] * 2

    temperature = GROQ_TEMPERATURE if provider == "Groq" else GROK_TEMPERATURE

    logger.info(
        "Generating story | provider=%s | model=%s | style=%s",
        provider, model, style_key
    )

    last_error: Exception | None = None
    max_retries = GROK_MAX_RETRIES  # shared retry count

    for attempt in range(1, max_retries + 1):
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=max_tokens,
                temperature=temperature,
            )
            story: str = response.choices[0].message.content or ""
            story = story.strip()
            logger.info("Story generated by %s (%d chars).", provider, len(story))
            return story

        except RateLimitError as exc:
            wait = 2 ** attempt
            logger.warning("%s rate limit (attempt %d/%d). Retrying in %ds…", provider, attempt, max_retries, wait)
            last_error = exc
            time.sleep(wait)

        except APIConnectionError as exc:
            wait = 2 ** attempt
            logger.warning("%s connection error (attempt %d/%d). Retrying in %ds…", attempt, max_retries, wait)
            last_error = exc
            time.sleep(wait)

        except APIStatusError as exc:
            logger.error("%s API error: %s — %s", provider, exc.status_code, exc.message)
            # If model not found, explain clearly
            if exc.status_code == 404 or "not found" in str(exc.message).lower():
                raise RuntimeError(
                    f"{provider} error: Model '{model}' not found. "
                    f"Please check if your API key has access to this model."
                ) from exc
            raise RuntimeError(
                f"{provider} API returned an error (HTTP {exc.status_code}): {exc.message}"
            ) from exc

        except Exception as exc:
            logger.exception("Unexpected error during story generation.")
            raise RuntimeError(f"Story generation failed unexpectedly: {exc}") from exc

    raise RuntimeError(
        f"Story generation failed after {max_retries} attempts with {provider}. "
        f"Last error: {last_error}"
    )
