"""
utils/file_helpers.py — File I/O helpers: saving uploads, packaging downloads.
"""

from __future__ import annotations

import io
import logging
import uuid
import zipfile
from pathlib import Path
from typing import Any

from config import TEMP_DIR

logger = logging.getLogger(__name__)


def save_uploaded_image(uploaded_file: Any) -> Path:
    """
    Persist an UploadedFile from Streamlit to the TEMP_DIR.

    A UUID prefix is added to avoid name collisions across concurrent users.

    Args:
        uploaded_file: The UploadedFile object from st.file_uploader.

    Returns:
        Path to the saved file.
    """
    ext = Path(uploaded_file.name).suffix.lower() or ".jpg"
    unique_name = f"{uuid.uuid4().hex}{ext}"
    dest = TEMP_DIR / unique_name

    with open(dest, "wb") as f:
        f.write(uploaded_file.getvalue())

    logger.info("Saved uploaded image to: %s", dest)
    return dest


def build_download_zip(
    audio_bytes: bytes,
    story_text: str,
    caption_text: str,
    audio_filename: str = "narrated_story.flac",
) -> bytes:
    """
    Package audio and story text into a downloadable ZIP archive in memory.

    Args:
        audio_bytes:    Raw audio content.
        story_text:     The generated story string.
        caption_text:   The BLIP-generated image caption.
        audio_filename: Filename to give the audio inside the ZIP.

    Returns:
        ZIP archive as bytes (ready to pass to st.download_button).
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(audio_filename, audio_bytes)
        zf.writestr("story.txt", story_text)
        zf.writestr("caption.txt", caption_text)
        zf.writestr(
            "README.txt",
            (
                "Generated by VisualVoice — AI Image-to-Story Narrator\n"
                "=====================================================\n\n"
                f"caption.txt  — Scene description from BLIP image captioning\n"
                f"story.txt    — Story generated by Grok LLM\n"
                f"{audio_filename} — Narrated audio from HuggingFace TTS\n"
            ),
        )
    return buf.getvalue()


def cleanup_temp_files() -> None:
    """
    Remove all files from TEMP_DIR older than the current process session.

    Safe to call on app startup; no-op if TEMP_DIR is empty.
    """
    removed = 0
    for f in TEMP_DIR.iterdir():
        if f.is_file():
            try:
                f.unlink()
                removed += 1
            except OSError as exc:
                logger.warning("Could not delete temp file %s: %s", f, exc)
    if removed:
        logger.info("Cleaned up %d temp file(s).", removed)
